### ISSUE TITLE
Having trouble with the image paths

### ISSUE THREAD

**Issue by drewrawitz** [DCzajkowski/vue-pure-lightbox#3]
I'm trying to reference a local image, like so:

```
<lightbox
  thumbnail="../../assets/workspace.jpg"
  :images="['../../assets/workspace.jpg']"
></lightbox>
```

For some reason, the watcher is not taking those paths and replacing them with the *actual* image path.  If I use that same path in an `img` tag, like this:

```
<img src="../../assets/workspace.jpg" alt="" />
```

Then it converts that into the real path which is: `/static/img/workspace.4b36834.jpg`.  

Do I need to change anything to get this plugin to pick that up? Or does this only support external / CDN hosted images?

Thanks!

**Comment by DCzajkowski** [comment]
Sorry I haven't wrote you back, but I didn't get any notification 😞 I guess you are using a Webpack loader that replaces urls. To be honest I don't know how to make it so that Webpack registers those relative paths. I hope you have already resolved your issue by now. If you have, it'd be awesome if you posted a solution. If not, I am worried I can't help.

Cheers

**Comment by DCzajkowski** [comment]
I am going to close this for now. If you have a solution, just post it here :)
